version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt
            nosetests -v tests
